name: Check Docs Links
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy Docs"]
    types:
      - completed

jobs:
  link-checker:
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ./dist-docs

      - name: Extract artifact
        run: |
          mkdir -p ./${{ github.event.repository.name }}
          tar -xf ./dist-docs/artifact.tar -C ./${{ github.event.repository.name }}

      - uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --root-dir .
            --verbose
            --no-progress
            --include-fragments
            './${{ github.event.repository.name }}/**/*.html'
          fail: true
